name: Auto Close Issue with Banned Keywords

on:
  issues:
    types: [opened]

jobs:
  close_if_banned:
    runs-on: ubuntu-latest
    steps:
      - name: Check for banned keywords in issue title or body
        uses: actions/github-script@v7
        with:
          script: |
            const bannedKeywords = ["刷星", "伪造"];
            const title = context.payload.issue.title || "";
            const body = context.payload.issue.body || "";
            const found = bannedKeywords.some(word => 
              title.includes(word) || body.includes(word)
            );

            if (found) {
              await github.issues.update({
                ...context.repo,
                issue_number: context.issue.number,
                state: "closed"
              });
            }
